### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by schneefux** [enmanuelduran/enmascript#1]
Hi, I really enjoy your blog and would like to follow it.
Can you consider adding an RSS/Atom feed? 😃

**Comment by enmanuelduran** [comment]
Hi @schneefux yes, of course, I can consider it, for now in the bottom of each article there is an email subscription box for you to get the updates, but I'll consider adding a RSS/Atom feed set up, thanks for the idea! :rocket:

**Comment by xxxtonixxx** [comment]
I'm interested in your RSS feed too :blush:

**Comment by enmanuelduran** [comment]
@schneefux @xxxtonixxx I have just added an RSS Feed available on https://enmascript.com/rss.xml 
 hope it's helpful to you guys and other developers to stay updated with the site :rocket:

If you have _any_ other comments, suggestions or improvements feel free to create another issue or make a PR and I'll gladly merge it if it makes sense and is correctly created.
